### ISSUE TITLE
[style] #15 Journey Challenge UI

### ISSUE THREAD

**Issue by teagh82** [team-journey/journey-android#15]
챌린지 뷰 레이아웃 시작
챌린지 시작전 뷰 ui 다 만들었고 챌린지 시작한 이후 만드는 중입니닷
일단 마진값 같은거 다 나오지 않은 것 같아서 임의로 설정했으니 다음에 변경할것임!

**Comment by jooyae** [comment]
-> 오늘 나머지 부분 제가 수정하겠습니다 ~!!
